//! Builds the native rive-runtime PLS (Vulkan) static libraries and the C++ FFI
//! shim, then emits the cargo link directives. Cross-platform:
//!
//! * **Linux**: premake5 `gmake2` -> `make`, compiled with **clang**; links the
//!   Vulkan loader dynamically.
//! * **Windows**: premake5 `vs2022` -> **MSBuild** with the **ClangCL** toolset
//!   (rive's default — its sources are not MSVC-clean), shim compiled with
//!   **clang-cl** to match the libs' ABI. The D3D shaders rive always builds on
//!   Windows are generated by the Windows SDK's `fxc`, and Vulkan is loaded at
//!   runtime from `vulkan-1.dll` (no import lib). The Vulkan SPIR-V shaders are
//!   generated by the **Vulkan SDK** (`glslangValidator` + `spirv-opt`) — this is
//!   the hermetic path used by CI and any clean checkout. As a local
//!   optimization, if the prebuilt SPIR-V headers are already in the tree (e.g.
//!   synced from a Linux build), rive's shader step finds them up-to-date and the
//!   SDK is not invoked. `build.rs` fails early (below) if NEITHER is available.
//!   Windows builds MUST run through `scripts/win.cmd`, which puts VS (clang-cl,
//!   MSBuild, fxc), the Vulkan SDK, GNU make, Git Bash `sh`, python and premake5
//!   on PATH.
//!
//! See ../../BUILD.md for the full toolchain notes and rationale.

use std::path::{Path, PathBuf};
use std::process::Command;

/// rive-runtime static-lib project names, in single-pass link order
/// (consumers before providers). `rive_shim` is prepended by `cc`.
///
/// These double as cargo link-names: `static={name}` resolves to `lib{name}.a`
/// on GNU and `{name}.lib` on MSVC/clang-cl, so the list is identical on both.
const RIVE_LIBS: &[&str] = &[
    "rive_pls_renderer",
    "rive",
    // Lua VM backing `--with_rive_scripting` (luigi-rosso/luau, cloned by premake).
    // rive's scripting TUs reference it, so it links AFTER `rive`
    // (provider-after-consumer). premake always emits this project — a `dummy.cpp`
    // stub when scripting is off — but it is only needed in the link with the flag on.
    "luau_vm",
    // miniaudio backing `--with_rive_audio=system` (rive-app/miniaudio, cloned by
    // premake). rive's audio TUs (audio_engine.cpp etc.) reference it, so it links
    // AFTER `rive` (provider-after-consumer), like `luau_vm`. premake always emits
    // the `miniaudio` project; it is only needed in the link with the audio flag on.
    "miniaudio",
    "rive_decoders",
    "libpng",
    "zlib",
    "libjpeg",
    "libwebp",
    "rive_harfbuzz",
    "rive_sheenbidi",
    "rive_yoga",
];

/// rive_vk_bootstrap sources compiled into the shim (rive does not build these
/// into any static lib). The swapchain/present path is intentionally excluded —
/// M0/M1.0 are headless/offscreen only. `vulkan_library.cpp` carries the
/// per-OS loader (`dlopen` on POSIX, `LoadLibraryA("vulkan-1.dll")` on Windows).
const BOOTSTRAP_SOURCES: &[&str] = &[
    "vulkan_instance.cpp",
    "vulkan_device.cpp",
    "vulkan_library.cpp",
    "vulkan_debug_callbacks.cpp",
    "vulkan_frame_synchronizer.cpp",
    "vulkan_headless_frame_synchronizer.cpp",
];

/// Pinned dependency tags (must match renderer/premake5_pls_renderer.lua).
const VULKAN_HEADERS_DIR: &str = "KhronosGroup_Vulkan-Headers_vulkan-sdk-1.4.321";
const VMA_DIR: &str = "GPUOpen-LibrariesAndSDKs_VulkanMemoryAllocator_v3.3.0";

/// How to build the rive static libs: the premake `--config` ("debug"/"release")
/// and whether to append `--no-lto`. Bundled so the per-OS builders take one
/// option object rather than two loose scalars.
struct RiveLibBuild<'a> {
    config: &'a str,
    no_lto: bool,
    /// rive's audio mode: "system" (rive owns the OS device + auto-plays) or
    /// "external" (rive owns no device; the host pulls the mixed PCM). Selected by
    /// the `audio-external` cargo feature.
    audio_mode: &'a str,
}

fn main() {
    let manifest_dir = PathBuf::from(env_var("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crate is at <workspace>/crates/rive-renderer-sys")
        .to_path_buf();

    let shim_dir = manifest_dir.join("shim");
    let rive_root = workspace_root.join("vendor/rive-runtime");
    let renderer_dir = rive_root.join("renderer");
    let premake_build_dir = rive_root.join("build");
    let deps_cache = workspace_root.join(".rive-deps");

    // Rebuild triggers.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=shim/rive_shim.h");
    println!("cargo:rerun-if-changed=shim/rive_shim_internal.hpp");
    println!("cargo:rerun-if-changed=shim/rive_shim.cpp");
    println!("cargo:rerun-if-changed=shim/rive_shim_viewmodel.cpp");
    println!("cargo:rerun-if-changed=shim/rive_shim_text.cpp");
    println!("cargo:rerun-if-changed=shim/rive_shim_rig.cpp");
    println!("cargo:rerun-if-changed=shim/rive_shim_audio.cpp");
    for var in [
        "CC",
        "CXX",
        "PREMAKE5",
        "RIVE_RUNTIME_CONFIG",
        "RIVE_RUNTIME_NO_LTO",
        "PROFILE",
    ] {
        println!("cargo:rerun-if-env-changed={var}");
    }
    println!("cargo:rerun-if-env-changed=RIVE_PREBUILT_LIBS");

    let windows = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows");

    // Windows/MSVC: rive-runtime forces the STATIC CRT (/MT) in its own build config, and
    // /MT cannot be mixed with /MD in one binary — so the cc-built shim, Rust std, and the
    // consuming crate must ALL use the static CRT, or the link dies with a wall of LNK2038
    // RuntimeLibrary mismatches (MT_StaticRelease vs MD_DynamicRelease) + libcpmt/msvcprt
    // double-definitions. cc picks /MT vs /MD from this target feature. `.cargo/config.toml`
    // is per-WORKSPACE, so a CONSUMER crate (e.g. a game pulling bevy-rive) does NOT inherit
    // rive-rust's setting and must enable it itself. Fail FAST here, before the cryptic link
    // error, with the exact remedy. (Applies to the prebuilt path too: rive's .libs are /MT.)
    let msvc = std::env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc");
    if windows && msvc && !target_feature_enabled("crt-static") {
        panic!(
            "rive-renderer-sys (Windows/MSVC) requires the STATIC CRT: rive-runtime forces /MT, \
             which cannot be mixed with /MD. Enable it in the CONSUMER crate's .cargo/config.toml \
             (NOT inherited across workspaces):\n\
             \n    [target.x86_64-pc-windows-msvc]\n    rustflags = [\"-C\", \"target-feature=+crt-static\"]\n\
             \nIf you already set rustflags (there, via [build], or the RUSTFLAGS env), MERGE \
             `+crt-static` in — cargo does NOT combine rustflags sources, one wins. Then \
             `cargo clean -p rive-renderer-sys` and rebuild. Without it the cc shim links /MD \
             while rive's libs are /MT -> LNK2038 RuntimeLibrary mismatch."
        );
    }

    // Prebuilt fast path (M-PKG.1): if pre-archived rive + shim libs are provided, link
    // them and skip the ENTIRE C++ build — premake, make/msbuild, the shader build, the
    // shim compile, and even the rive-runtime submodule. This removes the C++ toolchain
    // from a consumer's hot path. Produce the archive from a normal build (see BUILD.md §8).
    if let Some(dir) = std::env::var_os("RIVE_PREBUILT_LIBS") {
        link_prebuilt_libs(Path::new(&dir), windows);
        return;
    }

    ensure_submodule_present(&rive_root);
    std::fs::create_dir_all(&deps_cache).expect("create .rive-deps cache dir");
    let premake5 = find_premake5(&workspace_root, windows);

    // rive lib optimization config. Resolution order:
    //   1. RIVE_RUNTIME_CONFIG ("debug"/"release") wins, universally.
    //   2. else follow Cargo's PROFILE: `--release` -> release rive libs; dev -> debug.
    // The M1a/M1b dev loop uses the dev profile, so it keeps fast debug rive libs; a
    // `--release` build (e.g. the Windows perf relay) gets optimized rive libs. On
    // Windows rive forces /MT (release static runtime) regardless of config, so both
    // link against Rust's +crt-static cleanly.
    let rive_config = std::env::var("RIVE_RUNTIME_CONFIG").unwrap_or_else(|_| {
        match std::env::var("PROFILE").as_deref() {
            Ok("release") => "release".to_string(),
            _ => "debug".to_string(),
        }
    });

    // LTO: OFF by default for release on BOTH OSes (debug never sets it). This keeps
    // the final link working with each platform's default linker and needs no extra
    // toolchain:
    //   - Linux: rive's release LTO emits LLVM bitcode `.o`; the default `cc`->`ld`
    //     (bfd/gold) can't consume bitcode without the LLVMgold plugin, so `--no-lto`
    //     makes rive emit normal ELF objects ld links. (Verified: ELF, not bitcode.)
    //   - Windows: rive's vs2022/ClangCL/MSBuild release ALREADY emits COFF objects
    //     (verified: `64 86` COFF magic, not `BC` bitcode) that the default MSVC
    //     `link.exe` consumes — premake's `LinkTimeOptimization` flag doesn't reach
    //     clang-cl as `-flto` through MSBuild. So `--no-lto` is a harmless no-op here
    //     that we pass anyway to be explicit/deterministic (no silent bitcode if a
    //     future toolset starts honoring it). The anticipated "link.exe can't consume
    //     LTO bitcode" fight therefore does NOT materialize on this path — no
    //     `lld-link` needed. Non-LTO release is still a large step up from debug.
    // Override (future cross-module-LTO experiment): RIVE_RUNTIME_NO_LTO=0 forces LTO
    // ON — which then requires an LTO-capable final linker (set `linker = "lld-link"`
    // in .cargo/config.toml on Windows, or an ld with the LLVMgold plugin on Linux).
    // RIVE_RUNTIME_NO_LTO=1 forces it off. Unset = the per-config default below.
    let no_lto = match std::env::var("RIVE_RUNTIME_NO_LTO") {
        Ok(v) => !v.is_empty() && v != "0",
        Err(_) => rive_config == "release",
    };

    // Per-config out dir so debug/release artifacts never mix (a bare config switch in
    // one dir risks stale objects). Debug keeps the historical path verbatim, so
    // existing synced trees (and the prebuilt SPIR-V headers there) are undisturbed.
    // RIVE_BUILD_OUT is anchored to premake's CWD (renderer/), so `--out` is
    // concatenated onto it and must be RELATIVE.
    // Audio mode (cargo feature `audio-external`). Cargo re-runs build.rs when the
    // feature set changes, so CARGO_FEATURE_* is an authoritative trigger. External
    // mode is a DIFFERENT compile of librive + miniaudio (EXTERNAL_RIVE_AUDIO_ENGINE /
    // MA_NO_DEVICE_IO change the `AudioEngine` ABI and miniaudio's device path), so it
    // builds into its OWN out-dir (`-extaudio` suffix): switching modes never links a
    // stale archive (the make-keys-on-source-timestamps, not on -D flags, gotcha), at
    // the cost of a parallel tree + a one-time shader regen — exactly as the
    // debug/release out-dir split already behaves.
    let audio_external = std::env::var_os("CARGO_FEATURE_AUDIO_EXTERNAL").is_some();
    let audio_mode = if audio_external { "external" } else { "system" };
    let audio_suffix = if audio_external { "-extaudio" } else { "" };

    let out_rel = if rive_config == "release" {
        format!("out/rive-rust-m0-release{audio_suffix}")
    } else {
        format!("out/rive-rust-m0{audio_suffix}")
    };
    let rive_out = renderer_dir.join(&out_rel);
    let lib_build = RiveLibBuild {
        config: &rive_config,
        no_lto,
        audio_mode,
    };

    if windows {
        build_rive_libs_windows(
            &premake5,
            &renderer_dir,
            &premake_build_dir,
            &deps_cache,
            &out_rel,
            &rive_out,
            &lib_build,
        );
    } else {
        build_rive_libs_unix(
            &premake5,
            &renderer_dir,
            &premake_build_dir,
            &deps_cache,
            &out_rel,
            &rive_out,
            &lib_build,
        );
    }

    verify_archives(&rive_out, windows);
    compile_shim(&shim_dir, &rive_root, &renderer_dir, &rive_out, &deps_cache, windows, audio_external);
    emit_link_directives(&rive_out, windows);
}

// ---------------------------------------------------------------------------
// Step 1+2: build the rive-runtime static libs.
// ---------------------------------------------------------------------------

fn build_rive_libs_unix(
    premake5: &Path,
    renderer_dir: &Path,
    premake_build_dir: &Path,
    deps_cache: &Path,
    out_rel: &str,
    rive_out: &Path,
    build: &RiveLibBuild,
) {
    require_build_tools_unix();

    // Both premake (shader gen via clang) and make must use clang, not gcc.
    let cc = std::env::var("CC").unwrap_or_else(|_| "clang".into());
    let cxx = std::env::var("CXX").unwrap_or_else(|_| "clang++".into());

    // premake5 generates gmake2 Makefiles (and runs the shader build). `--no-lto`
    // (a release-only rive option) is appended for non-LTO linkers; `Option<&str>`
    // is a 0-or-1 element iterator, so it is a no-op when LTO stays on.
    //
    // Audio: `=system` (default) — rive owns a miniaudio device that plays audio
    // events straight to the OS output (WITH_RIVE_AUDIO). `=external` (the
    // `audio-external` cargo feature) — rive owns NO device; the host pulls the mixed
    // PCM for its own mixer (EXTERNAL_RIVE_AUDIO_ENGINE + MA_NO_DEVICE_IO).
    let audio_arg = format!("--with_rive_audio={}", build.audio_mode);
    run(
        Command::new(premake5)
            .current_dir(renderer_dir)
            .env("PREMAKE_PATH", premake_build_dir)
            .env("DEPENDENCIES", deps_cache)
            .env("CC", &cc)
            .env("CXX", &cxx)
            .args([
                "gmake2",
                &format!("--config={}", build.config),
                &format!("--out={out_rel}"),
                "--with_vulkan",
                "--with_rive_text",
                "--with_rive_layout",
                "--with_rive_scripting",
                &audio_arg,
                "--no-download-progress",
            ])
            .args(build.no_lto.then_some("--no-lto")),
        "premake5 gmake2 (generate Makefiles + shaders)",
    );

    // make builds the explicit static-lib targets (never `all`: it needs GLFW).
    let jobs = std::env::var("NUM_JOBS").unwrap_or_else(|_| "4".into());
    run(
        Command::new("make")
            .current_dir(renderer_dir)
            .env("DEPENDENCIES", deps_cache)
            .env("CC", &cc)
            .env("CXX", &cxx)
            .arg("-C")
            .arg(rive_out)
            .arg("config=default") // the ONLY premake configuration is "default"
            .arg(format!("-j{jobs}"))
            .args(RIVE_LIBS),
        "make (build rive-runtime static libs)",
    );
}

fn build_rive_libs_windows(
    premake5: &Path,
    renderer_dir: &Path,
    premake_build_dir: &Path,
    deps_cache: &Path,
    out_rel: &str,
    rive_out: &Path,
    build: &RiveLibBuild,
) {
    require_build_tools_windows(premake5, rive_out);

    // premake5 vs2022 with rive's DEFAULT toolset (clang -> the ClangCL platform
    // toolset). rive's sources are written for clang and are not MSVC-clean, so
    // --toolset=msc fails to compile them. This step also runs the configure-time
    // shader build (`make -C src/shaders ... d3d spirv`): `spirv` reuses the
    // prebuilt SPIR-V headers (no glslangValidator/spirv-opt), `d3d` is generated
    // by the Windows SDK's fxc. Requires sh+make+python+fxc on PATH (win.cmd).
    // No CC/CXX env: vs2022 ignores them and selects ClangCL from the project.
    let audio_arg = format!("--with_rive_audio={}", build.audio_mode);
    run(
        Command::new(premake5)
            .current_dir(renderer_dir)
            .env("PREMAKE_PATH", premake_build_dir)
            .env("DEPENDENCIES", deps_cache)
            .args([
                "vs2022",
                &format!("--config={}", build.config),
                &format!("--out={out_rel}"),
                "--with_vulkan",
                "--with_rive_text",
                "--with_rive_layout",
                "--with_rive_scripting",
                // Audio mode: `=system` (default) or `=external` (the `audio-external`
                // cargo feature → host-pulled PCM). See the gmake2 builder for detail.
                &audio_arg,
                "--no-download-progress",
            ])
            .args(build.no_lto.then_some("--no-lto")),
        "premake5 vs2022 (generate solution + shaders)",
    );

    // MSBuild the explicit lib targets (never the whole solution: it includes
    // path_fiddle/glfw3). Project names == MSBuild targets. /p:Platform=x64 picks
    // the x64 ClangCL toolset regardless of the host dev-shell arch.
    let jobs = std::env::var("NUM_JOBS").unwrap_or_else(|_| "4".into());
    let targets = RIVE_LIBS.join(";");
    run(
        Command::new("msbuild.exe")
            .current_dir(rive_out)
            .arg("rive.sln")
            .arg("-p:Configuration=default")
            .arg("-p:Platform=x64")
            .arg(format!("-m:{jobs}"))
            .arg(format!("-t:{targets}"))
            .arg("-v:minimal")
            .arg("-nologo"),
        "msbuild (build rive-runtime static libs, ClangCL/x64)",
    );
}

// ---------------------------------------------------------------------------
// Step 3: compile the C++ shim (+ bootstrap sources).
// ---------------------------------------------------------------------------

fn compile_shim(
    shim_dir: &Path,
    rive_root: &Path,
    renderer_dir: &Path,
    rive_out: &Path,
    deps_cache: &Path,
    windows: bool,
    audio_external: bool,
) {
    let vk_headers_inc = deps_cache.join(VULKAN_HEADERS_DIR).join("include");
    let vma_inc = deps_cache.join(VMA_DIR).join("include");
    assert!(
        vk_headers_inc.join("vulkan/vulkan.h").exists(),
        "Vulkan headers not found at {} — premake should have cloned them. \
         Check network/git access during the premake step.",
        vk_headers_inc.display()
    );

    let mut build = cc::Build::new();
    build
        .cpp(true)
        .std("c++17")
        .define("RIVE_VULKAN", None)
        .define("VK_NO_PROTOTYPES", None)
        .define("VMA_STATIC_VULKAN_FUNCTIONS", "0")
        .define("VMA_DYNAMIC_VULKAN_FUNCTIONS", "1")
        // Match librive's audio build (--with_rive_audio=system) so any class whose
        // layout is #ifdef WITH_RIVE_AUDIO stays ABI-identical across the shim ↔
        // librive boundary, and the rive audio headers are visible to the shim.
        .define("WITH_RIVE_AUDIO", None)
        // The pinned Vulkan/VMA headers MUST come first so `<vulkan/vulkan.h>`
        // resolves to the vendored copy, not any system header.
        .include(&vk_headers_inc)
        .include(&vma_inc)
        .include(shim_dir)
        .include(rive_root.join("include"))
        .include(renderer_dir.join("include"))
        // renderer/src for `#include "shaders/constants.glsl"`, and the
        // generated-headers dir for the SPIR-V/shader headers.
        .include(renderer_dir.join("src"))
        .include(rive_out.join("include"))
        .include(rive_root.join("decoders/include"))
        .include(renderer_dir.join("rive_vk_bootstrap/include"))
        .file(shim_dir.join("rive_shim.cpp"))
        // Per-feature shim TUs (see rive_shim_internal.hpp). One .cpp per feature.
        .file(shim_dir.join("rive_shim_viewmodel.cpp"))
        .file(shim_dir.join("rive_shim_text.cpp"))
        .file(shim_dir.join("rive_shim_rig.cpp"))
        .file(shim_dir.join("rive_shim_audio.cpp"));

    // External audio mode (cargo feature `audio-external`) gives `rive::AudioEngine`
    // an extra `#ifdef EXTERNAL_RIVE_AUDIO_ENGINE` member (`m_readFrames`) and exposes
    // its `readAudioFrames`/`sumAudioFrames` methods. The shim includes
    // audio_engine.hpp, so it MUST define the same flag or the class layout mismatches
    // across the shim<->librive boundary (the same ABI-parity rule as WITH_RIVE_AUDIO).
    // MA_NO_DEVICE_IO / MA_NO_RESOURCE_MANAGER only gate miniaudio.h (not included
    // here), so they are not needed in the shim.
    if audio_external {
        build.define("EXTERNAL_RIVE_AUDIO_ENGINE", None);
    }

    if windows {
        // Match the rive libs (built with clang-cl): compiling the shim with
        // clang-cl gives it the same `__clang__` SIMD representation as the libs
        // (rive's simd.hpp uses clang ext_vector_type under __clang__, a struct
        // polyfill otherwise), avoiding a struct-layout/ABI mismatch across the
        // shim<->lib boundary. clang-cl takes MSVC-style flags. /MT vs /MTd is
        // driven by Rust's crt-static + profile (cc honors it).
        build.compiler("clang-cl");
        build.flag("/GR-"); // no RTTI (matches rive's ABI)
        build.flag("/EHsc"); // exceptions for the shim boundary
        // Mirror rive's own Windows defines (rive_build_config.lua) so the shim +
        // bootstrap sources see <windows.h> and rive's headers identically to how
        // the libs were compiled. NOMINMAX is load-bearing: without it the Win32
        // loader path pulls in <windows.h>'s max/min macros, which break
        // std::numeric_limits<uint32_t>::max() in vulkan_device.cpp.
        build.define("NOMINMAX", None);
        build.define("_USE_MATH_DEFINES", None);
        build.define("RIVE_WINDOWS", None);
        build.define("_CRT_SECURE_NO_WARNINGS", None); // getenv() etc.
    } else {
        let cxx = std::env::var("CXX").unwrap_or_else(|_| "clang++".into());
        build
            .compiler(&cxx)
            .flag("-fno-rtti"); // match rive's ABI; exceptions left on
    }

    let bootstrap_src = renderer_dir.join("rive_vk_bootstrap/src");
    for src in BOOTSTRAP_SOURCES {
        let path = bootstrap_src.join(src);
        assert!(path.exists(), "missing bootstrap source: {}", path.display());
        build.file(&path);
    }
    // cc emits `cargo:rustc-link-lib=static=rive_shim` + its search path FIRST,
    // so the shim precedes the rive libs in the link line.
    build.compile("rive_shim");
}

// ---------------------------------------------------------------------------
// Step 4: link directives.
// ---------------------------------------------------------------------------

fn emit_link_directives(rive_out: &Path, windows: bool) {
    println!("cargo:rustc-link-search=native={}", rive_out.display());
    for lib in RIVE_LIBS {
        println!("cargo:rustc-link-lib=static={lib}");
    }
    emit_system_link_directives(windows);
}

/// The OS link companions (Vulkan loader + C++/libc runtime), shared by the from-source
/// and the prebuilt link paths so both produce an identical final link line.
fn emit_system_link_directives(windows: bool) {
    if windows {
        // Vulkan is resolved at runtime via LoadLibraryA("vulkan-1.dll") (rive is
        // built VK_NO_PROTOTYPES), so there is NO Vulkan import lib to link — the
        // NVIDIA driver's vulkan-1.dll satisfies it at runtime. The MSVC CRT,
        // kernel32 (LoadLibrary), user32, etc. are linked by default. Add Windows
        // system libs here only if the linker reports unresolved symbols.
    } else {
        // Vulkan loader (dynamic; rive uses VK_NO_PROTOTYPES + a runtime loader),
        // the C++ runtime, and libc companions. stdc++ must follow the archives.
        println!("cargo:rustc-link-lib=dylib=vulkan");
        println!("cargo:rustc-link-lib=dylib=stdc++");
        println!("cargo:rustc-link-lib=dylib=pthread");
        println!("cargo:rustc-link-lib=dylib=dl");
        println!("cargo:rustc-link-lib=dylib=m");
    }
}

/// Links pre-archived rive + shim static libs from `dir`, skipping premake/make/clang
/// entirely (and not even requiring the rive-runtime submodule). Set via
/// `RIVE_PREBUILT_LIBS=<dir>`. `dir` must contain EVERY archive a from-source build
/// produces — the rive libs (this platform's naming) plus `cc`'s shim archive.
fn link_prebuilt_libs(dir: &Path, windows: bool) {
    assert!(
        dir.is_dir(),
        "RIVE_PREBUILT_LIBS={} is not a directory",
        dir.display()
    );

    let shim = if windows { "rive_shim.lib" } else { "librive_shim.a" };
    let mut expected = rive_archive_file_names(windows);
    expected.push(shim.to_string());
    let missing: Vec<&str> = expected
        .iter()
        .map(String::as_str)
        .filter(|f| !dir.join(f).exists())
        .collect();
    assert!(
        missing.is_empty(),
        "RIVE_PREBUILT_LIBS={} is missing archives: {missing:?}\n\
         Produce them with a normal from-source build, then copy the rive libs from \
         vendor/rive-runtime/renderer/out/rive-rust-m0[-release]/ AND {shim} from the \
         build's OUT_DIR into this dir. See BUILD.md §8.",
        dir.display()
    );

    println!(
        "cargo:warning=rive-renderer-sys: linking PREBUILT libs from {} (skipped premake/make/clang + the rive-runtime submodule)",
        dir.display()
    );
    // Single-pass link order: shim (consumer) before the rive libs (providers), then
    // the system companions — identical to the from-source path (cc emits the shim first).
    println!("cargo:rustc-link-search=native={}", dir.display());
    println!("cargo:rustc-link-lib=static=rive_shim");
    for lib in RIVE_LIBS {
        println!("cargo:rustc-link-lib=static={lib}");
    }
    emit_system_link_directives(windows);
}

// ---------------------------------------------------------------------------
// Helpers.
// ---------------------------------------------------------------------------

fn env_var(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| panic!("missing env var {key}"))
}

/// True if `feat` is in `CARGO_CFG_TARGET_FEATURE` — the effective enabled target features
/// cargo passes to build scripts (reflecting `+crt-static` from a config `rustflags` OR the
/// `RUSTFLAGS` env, whichever the consumer used).
fn target_feature_enabled(feat: &str) -> bool {
    std::env::var("CARGO_CFG_TARGET_FEATURE")
        .map(|f| f.split(',').any(|x| x == feat))
        .unwrap_or(false)
}

fn ensure_submodule_present(rive_root: &Path) {
    if !rive_root.join("renderer/premake5.lua").exists() {
        panic!(
            "rive-runtime submodule not found at {}.\n\
             Run:  git submodule update --init --recursive",
            rive_root.display()
        );
    }
}

/// Resolves premake5 from `$PREMAKE5`, then the vendored binary, then `PATH`.
/// Windows requires premake **5.0.0-beta7** (`tools/premake5.exe`); beta2
/// mistranslates rive's `fatalwarnings({'All'})` to the bogus MSVC flag `/weAll`.
/// Linux uses the vendored ELF `tools/premake5` (beta2 is fine for gmake/clang).
fn find_premake5(workspace_root: &Path, windows: bool) -> PathBuf {
    if let Ok(p) = std::env::var("PREMAKE5") {
        return PathBuf::from(p);
    }
    let rel = if windows { "tools/premake5.exe" } else { "tools/premake5" };
    let vendored = workspace_root.join(rel);
    if vendored.is_file() {
        return vendored;
    }
    if command_succeeds("premake5", &["--version"]) {
        return PathBuf::from("premake5");
    }
    let fetch = if windows {
        "tools/fetch_premake.cmd"
    } else {
        "tools/fetch_premake.sh"
    };
    panic!(
        "premake5 not found. Expected the vendored binary at {} (run {fetch} or \
         see BUILD.md), or premake5 on PATH, or set $PREMAKE5.",
        vendored.display()
    );
}

/// Fails the Linux build with one actionable message listing every missing tool.
fn require_build_tools_unix() {
    // (binary, version-probe args, apt package, why it is needed)
    let tools: &[(&str, &[&str], &str, &str)] = &[
        ("clang", &["--version"], "clang", "C++ compiler (rive uses clang vector builtins; gcc is unsupported)"),
        ("clang++", &["--version"], "clang", "C++ compiler driver for the shim"),
        ("make", &["--version"], "make", "runs the generated gmake2 Makefiles + the shader build"),
        ("python3", &["--version"], "python3", "rive's offline shader minify/codegen"),
        ("glslangValidator", &["--version"], "glslang-tools", "compiles rive's Vulkan GLSL to SPIR-V"),
        ("spirv-opt", &["--version"], "spirv-tools", "optimizes rive's SPIR-V shaders"),
        ("git", &["--version"], "git", "premake clones Vulkan-Headers/VMA/etc. at configure time"),
    ];
    let missing: Vec<&(&str, &[&str], &str, &str)> = tools
        .iter()
        .filter(|(bin, args, _, _)| !command_succeeds(bin, args))
        .collect();
    if !missing.is_empty() {
        let mut msg = String::from("Missing required build tools:\n");
        let mut pkgs = Vec::new();
        for (bin, _, pkg, why) in &missing {
            msg.push_str(&format!("  - {bin}: {why}\n"));
            pkgs.push(*pkg);
        }
        pkgs.sort_unstable();
        pkgs.dedup();
        msg.push_str(&format!("\nOn Ubuntu: sudo apt-get install -y {}\n", pkgs.join(" ")));
        msg.push_str("(libvulkan-dev provides the Vulkan loader dev symlink for linking.)");
        panic!("{msg}");
    }

    // Vulkan loader dev symlink (libvulkan.so) is needed to link -lvulkan.
    let has_loader = [
        "/usr/lib/x86_64-linux-gnu/libvulkan.so",
        "/usr/lib/libvulkan.so",
        "/lib/x86_64-linux-gnu/libvulkan.so",
    ]
    .iter()
    .any(|p| Path::new(p).exists())
        || std::env::var("VULKAN_SDK").is_ok();
    if !has_loader {
        panic!(
            "Vulkan loader dev symlink (libvulkan.so) not found.\n\
             On Ubuntu: sudo apt-get install -y libvulkan-dev"
        );
    }
}

/// Verifies the Windows build environment. The toolchain (VS clang-cl + MSBuild,
/// Windows SDK fxc, GNU make, Git Bash sh, python, premake) is provided by
/// `scripts/win.cmd`; if MSBuild is absent we are almost certainly NOT running
/// under it, so point the user there rather than failing cryptically later.
fn require_build_tools_windows(premake5: &Path, rive_out: &Path) {
    assert!(
        premake5.exists() || premake5.as_os_str() == "premake5",
        "premake5 not found at {}",
        premake5.display()
    );
    // Always needed (independent of shader provenance).
    let tools: &[(&str, &[&str], &str)] = &[
        ("msbuild.exe", &["-version", "-nologo"], "builds the rive .libs (vs2022/ClangCL)"),
        ("clang-cl", &["--version"], "compiles the shim + rive (rive's default toolset)"),
        ("make", &["--version"], "runs rive's configure-time shader build"),
        ("python", &["--version"], "rive's shader minify/codegen"),
        ("sh", &["--version"], "shell for the shader Makefile recipes (Git Bash)"),
    ];
    let missing: Vec<&str> = tools
        .iter()
        .filter(|(bin, args, _)| !command_succeeds(bin, args))
        .map(|(bin, _, _)| *bin)
        .collect();
    if !missing.is_empty() {
        panic!(
            "Windows build environment incomplete (missing: {}).\n\
             Build through the relay so VS (clang-cl, MSBuild, fxc), GNU make, \
             Git Bash sh, python and premake are on PATH:\n\
             \n    scripts\\win.cmd build --release\n\
             \nor, from WSL2:\n\
             \n    cmd.exe /c \"scripts\\win.cmd run --release --example offscreen_png -- assets\\coffee_loader.riv out.png\"\n\
             \nThe \"C++ Clang tools for Windows\" VS component is required. See BUILD.md.",
            missing.join(", ")
        );
    }

    // Shader provenance (hermeticity guard). rive's Vulkan SPIR-V is produced by
    // glslangValidator + spirv-opt (the Vulkan SDK). The HERMETIC path — used by
    // CI and any clean checkout — has the SDK installed and generates the SPIR-V
    // natively. The LOCAL fast path reuses prebuilt SPIR-V headers already in the
    // tree (e.g. synced from a Linux build) and skips the SDK. If NEITHER is
    // present, rive's shader step would fail deep inside `make` with a cryptic
    // "glslangValidator: not found" — so fail here with the actionable remedy.
    let spirv_dir = rive_out.join("include/generated/shaders/spirv");
    let spirv_prebuilt = std::fs::read_dir(&spirv_dir)
        .is_ok_and(|d| d.flatten().any(|e| e.path().extension().is_some_and(|x| x == "h")));
    let sdk_tools = command_succeeds("glslangValidator", &["--version"])
        && command_succeeds("spirv-opt", &["--version"]);
    if !spirv_prebuilt && !sdk_tools {
        panic!(
            "Cannot obtain rive's Vulkan SPIR-V shaders on Windows.\n\
             Neither prebuilt SPIR-V headers ({}) nor the Vulkan SDK \
             (glslangValidator + spirv-opt, to generate them) is present.\n\
             Fix one of:\n\
             - Install the LunarG Vulkan SDK (sets VULKAN_SDK; the relay adds its \
             Bin to PATH). This is the hermetic CI path.\n\
             - Build from a working tree that already contains the prebuilt SPIR-V \
             (e.g. synced from a Linux build via scripts/sync_to_windows.sh).\n\
             See BUILD.md §1b.",
            spirv_dir.display()
        );
    }
}

fn command_succeeds(bin: &str, args: &[&str]) -> bool {
    Command::new(bin)
        .args(args)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn run(cmd: &mut Command, label: &str) {
    eprintln!("[rive-renderer-sys] {label}: {cmd:?}");
    let status = cmd
        .status()
        .unwrap_or_else(|e| panic!("failed to spawn `{label}`: {e}"));
    if !status.success() {
        panic!("`{label}` failed with status {status}. Command: {cmd:?}");
    }
}

/// The rive static-lib archive FILE names this platform produces, in `RIVE_LIBS` order.
/// On GNU, premake prefixes "lib" (so `libpng` → `liblibpng.a`, the image libs getting a
/// double "lib" because their project names already start with "lib"); on MSVC/clang-cl
/// there is no prefix and the extension is `.lib`. Shared by `verify_archives` (from
/// source) and `link_prebuilt_libs` so both agree on the exact file set.
fn rive_archive_file_names(windows: bool) -> Vec<String> {
    RIVE_LIBS
        .iter()
        .map(|l| {
            if windows {
                format!("{l}.lib")
            } else {
                format!("lib{l}.a")
            }
        })
        .collect()
}

fn verify_archives(rive_out: &Path, windows: bool) {
    let files = rive_archive_file_names(windows);
    let missing: Vec<&str> = files
        .iter()
        .map(String::as_str)
        .filter(|f| !rive_out.join(f).exists())
        .collect();
    if !missing.is_empty() {
        panic!(
            "rive-runtime build did not produce: {missing:?}\nin {}",
            rive_out.display()
        );
    }
}
